In [ ]:
# REGular Expression : in a separate notebook called Regex.ipynb


#Module 4 : Introduction to Numpy , Pandas and Matplotlib 


#Module 5 : Data Manipulation (Pandas) : groupby join concat iter




In [ ]:
python

list
tuple
set
dict
str

In [1]:
import numpy as np

In [ ]:
#arrays : arrays are used to store values of homogenus dataypes 

In [ ]:
ndarry 

In [22]:
n1=np.array([1,2,3,4])

In [23]:
n1

array([1, 2, 3, 4])

In [24]:
type(n1)

numpy.ndarray

In [14]:
age=[11,12,13,14]
height=[150,151,152,153]
weight=[110,112,113,114]

In [15]:
details=[age,height,weight]

In [16]:
n2=np.array(details)

In [17]:
n2

array([[ 11,  12,  13,  14],
       [150, 151, 152, 153],
       [110, 112, 113, 114]])

In [18]:
n1.ndim

1

In [19]:
n2.ndim

2

In [25]:
n1.size

4

In [21]:
n2.size

12

In [26]:
n1.shape

(4,)

In [27]:
n1

array([1, 2, 3, 4])

In [28]:
n2.shape

(3, 4)

In [29]:
n2

array([[ 11,  12,  13,  14],
       [150, 151, 152, 153],
       [110, 112, 113, 114]])

In [30]:
import pandas as pd

In [32]:
df1=pd.DataFrame(n2)

In [33]:
df1.index=['Age','Height','Weight']

In [34]:
df1

0    1    2    3
Age      11   12   13   14
Height  150  151  152  153
Weight  110  112  113  114

In [37]:
df1=df1.transpose()

In [39]:
df1['Age']=df1['Age']+1

In [40]:
df1

Age  Height  Weight
0   12     150     110
1   13     151     112
2   14     152     113
3   15     153     114

In [42]:
type(df1.values)

numpy.ndarray

In [43]:
n1

array([1, 2, 3, 4])

In [44]:
n2

array([[ 12,  13,  14,  15],
       [150, 151, 152, 153],
       [110, 112, 113, 114]])

In [47]:
n1*2   #element by element operation 

array([2, 4, 6, 8])

In [46]:
[1,2,3,4]*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
#Indexing 0 based 


#Slicing 

#Mutable 

In [50]:
n1[0]=11

In [51]:
n1

array([11,  2,  3,  4])

In [52]:
list(n1)

[11, 2, 3, 4]

In [53]:
numbers=[11,22,33,44,55,66]

In [54]:
np.asarray(numbers)

array([11, 22, 33, 44, 55, 66])

In [57]:
n1[0]=234

In [58]:
n1

array([234,   2,   3,   4])

In [59]:
details=['Yash','Saxena',6.1,33,'Berlin']

In [60]:
type(details)

list

In [61]:
np.array(details)   

array(['Yash', 'Saxena', '6.1', '33', 'Berlin'], dtype='<U6')

In [62]:
n2

array([[ 12,  13,  14,  15],
       [150, 151, 152, 153],
       [110, 112, 113, 114]])

In [64]:
n2[0]

array([12, 13, 14, 15])

In [66]:
for each in n2:
    print (each,type(each))
    print ()

[12 13 14 15] <class 'numpy.ndarray'>

[150 151 152 153] <class 'numpy.ndarray'>

[110 112 113 114] <class 'numpy.ndarray'>



In [67]:
n2

array([[ 12,  13,  14,  15],
       [150, 151, 152, 153],
       [110, 112, 113, 114]])

In [68]:
n2[0]

array([12, 13, 14, 15])

In [70]:
n2[0:2]

array([[ 12,  13,  14,  15],
       [150, 151, 152, 153]])

In [71]:
n2[1:]

array([[150, 151, 152, 153],
       [110, 112, 113, 114]])

In [72]:
n2[:]

array([[ 12,  13,  14,  15],
       [150, 151, 152, 153],
       [110, 112, 113, 114]])

In [74]:
n2[:,0:2]

array([[ 12,  13],
       [150, 151],
       [110, 112]])

In [78]:
n2[1:,:3]

array([[150, 151, 152],
       [110, 112, 113]])

In [ ]:
n2[row_starting:row_ending:row_skip , col_starting:col_ending :col_skip ]

In [79]:
n2

array([[ 12,  13,  14,  15],
       [150, 151, 152, 153],
       [110, 112, 113, 114]])

In [91]:
n2[::2,::3]

array([[ 12,  15],
       [110, 114]])

In [93]:
n2.reshape(2,6)

array([[ 12,  13,  14,  15, 150, 151],
       [152, 153, 110, 112, 113, 114]])

In [84]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [86]:
np.zeros((3,4))+1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
import Screen

Enter a directory name :screen6
Enter seconds :3
Directory exists 


In [ ]:
#numpy 


mean, median , mode 

std 